#!/usr/bin/env python3

import os
from diffusers import DiffusionPipeline
from concurrent.futures import ThreadPoolExecutor
import requests

MODEL_CACHE = "diffusers-cache"
model_id = "redstonehero/epicrealism_pureevolutionv5"

os.makedirs(MODEL_CACHE, exist_ok=True)

loras = [
    { "name": "detail_tweaker", "url": "https://civitai.com/api/download/models/62833" },
    { "name": "beauty_face_lip_filler", "url": "https://civitai.com/api/download/models/32950?type=Model&format=SafeTensor&size=full&fp=fp16" },
    { "name": "more_detailed_beautiful", "url": "https://civitai.com/api/download/models/167778" },
    { "name": "eyeliner", "url": "https://civitai.com/api/download/models/140229?type=Model&format=SafeTensor" },
    { "name": "bimbo_makeup", "url": "https://civitai.com/api/download/models/22398?type=Model&format=SafeTensor&size=full&fp=fp16" },
    { "name": "yoga_pants", "url": "https://civitai.com/api/download/models/137700" },
    { "name": "exercise_fitness_yoga_training_professional_movements", "url": "https://civitai.com/api/download/models/103540?type=Model&format=SafeTensor" },
    { "name": "jjs_interior_space_gym", "url": "https://civitai.com/api/download/models/210580" },
    { "name": "yoga_pants_by_stable_yogi", "url": "https://civitai.com/api/download/models/204182?type=Model&format=SafeTensor" }, # no images on civitai for this one
    { "name": "yoga_poses", "url": "https://civitai.com/api/download/models/125073" },
    { "name": "yoga_studio", "url": "https://civitai.com/api/download/models/152384" },
    { "name": "muscle_slider", "url": "https://civitai.com/api/download/models/121658?type=Model&format=SafeTensor" },
    { "name": "sexy_fitness_trainer", "url": "https://civitai.com/api/download/models/152527?type=Model&format=SafeTensor"},
    { "name": "sports_bra_gym_shorts_collection", "url": "https://civitai.com/api/download/models/291471?type=Model&format=SafeTensor" },
    { "name": "gym_girl_pose", "url": "https://civitai.com/api/download/models/257033?type=Model&format=SafeTensor" },
    { "name": "gym_shorts", "url": "https://civitai.com/api/download/models/275369" },
    { "name": "morphed_muscle", "url": "https://civitai.com/api/download/models/26411?type=Model&format=SafeTensor&size=full&fp=fp16" },
    { "name": "dance_dresses_collection", "url": "https://civitai.com/api/download/models/98734" },
    { "name": "oily_body_dancing_Girl", "url": "https://civitai.com/api/download/models/178535?type=Model&format=SafeTensor" }, 
    { "name": "dancer_of_the_desert", "url": "https://civitai.com/api/download/models/46695" },
    { "name": "dance_photography", "url": "https://civitai.com/api/download/models/101765" },
    { "name": "dancers_real_photos", "url": "https://civitai.com/api/download/models/145384?type=Model&format=SafeTensor" },
    { "name": "gymnast_outfit", "url": "https://civitai.com/api/download/models/68849" }, 
    { "name": "figure_skating_dresses_clothing", "url": "https://civitai.com/api/download/models/106332?type=Model&format=SafeTensor" }, 
    { "name": "open_pose_gymnastics", "url": "https://civitai.com/api/download/models/281727" },
    { "name": "high_fashion_galliano_for_dior", "url": "https://civitai.com/api/download/models/168178?type=Model&format=SafeTensor" },
    { "name": "flowers_fashion", "url": "https://civitai.com/api/download/models/191498?type=Model&format=SafeTensor" },
    { "name": "heaven_hell_fashion", "url": "https://civitai.com/api/download/models/209096?type=Model&format=SafeTensor" },
    { "name": "korean_style_fashion_trench_coat", "url": "https://civitai.com/api/download/models/266741" },
    { "name": "design_fashion", "url": "https://civitai.com/api/download/models/203603?type=Model&format=SafeTensor" },
    { "name": "modern_victorian_fashion_dress ", "url": "https://civitai.com/api/download/models/189837?type=Model&format=SafeTensor" },
    { "name": "world_travel_guide_Season_1", "url": "https://civitai.com/api/download/models/109096?type=Model&format=SafeTensor" },
    { "name": "masterpieces_of_natures_craftsmanship", "url": "https://civitai.com/api/download/models/135500" }
]

def download_file(lora):
    local_filename = MODEL_CACHE + "/" + lora["name"] + ".safetensors"
    url = lora["url"]

    with requests.get(url, stream=True) as r:
        r.raise_for_status()
        # Get the total file size from headers
        total_length = r.headers.get('content-length')
        if total_length is not None:  # [1]
            total_length = int(total_length)
        else:
            print(f"Could not get content-length from {url}, download size unknown.")
        
        downloaded = 0
        with open(local_filename, 'wb') as f:
            for chunk in r.iter_content(chunk_size=8192):
                if chunk:  # filter out keep-alive new chunks
                    f.write(chunk)
                    downloaded += len(chunk)
                    done_percentage = int(50 * downloaded / total_length) if total_length else '?'
                    print(f'\rDownloading {local_filename}: [{"#" * done_percentage}{"." * (50-done_percentage)}] {downloaded}/{total_length} bytes', end='', flush=True)
        print()  # Newline for clean output after download
    return local_filename

def download_files():
    print(f"Download {len(loras)} loras")
    with ThreadPoolExecutor(max_workers=5) as executor:
        executor.map(download_file, loras)

download_files()

pipe = DiffusionPipeline.from_pretrained(model_id, cache_dir=MODEL_CACHE)