#!/usr/bin/env python3


import os
# from diffusers import StableDiffusionImg2ImgPipeline
import requests


# model_id = "runwayml/stable-diffusion-v1-5"
# MODEL_CACHE = "diffusers-cache"

def download_large_file(url, filename):
    """Download a large file in chunks."""
    with requests.get(url, stream=True) as r:
        r.raise_for_status()
        with open(filename, 'wb') as f:
            for chunk in r.iter_content(chunk_size=8192): 
                f.write(chunk)

# URL of the large file you want to download
large_file_url = 'https://civitai.com/api/download/models/143906?type=Model&format=SafeTensor&size=pruned&fp=fp16'
output_filename = 'mymodel.safetensors'

# Download the large file
download_large_file(large_file_url, output_filename)

# os.makedirs(MODEL_CACHE, exist_ok=True)

# pipe = StableDiffusionImg2ImgPipeline.from_pretrained(
#     model_id,
#     cache_dir=MODEL_CACHE,
# )